# Generated by Django 5.1.7 on 2025-04-26 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_type', models.CharField(choices=[('EXEC', 'Executive Committee'), ('PM', 'Portfolio Manager'), ('SA', 'Senior Analyst')], max_length=4)),
                ('industry_group', models.CharField(choices=[('TMT', 'Tech, Media & Telecom'), ('RELG', 'Real Estate, Gaming & Lodging'), ('FI', 'Financial Institutions'), ('HLS', 'Healthcare & Life Sciences'), ('CR', 'Consumer & Retail'), ('NR', 'Natural Resources'), ('IND', 'Industrials'), ('NONE', 'None')], default='NONE', max_length=5)),
                ('exec_role', models.CharField(choices=[('CIO', 'Chief Investment Officer'), ('CHAIR', 'Co-Chair'), ('CAO', 'Chief Administrative Officer'), ('COO', 'Chief Operating Officer'), ('NONE', 'None')], default='NONE', max_length=5)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('transaction_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
