# Generated by Django 5.1.7 on 2025-06-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': [models.Case(models.When(exec_role='CHAIR', then=models.Value(1)), models.When(exec_role='CIO', then=models.Value(2)), models.When(exec_role='CAO', then=models.Value(3)), models.When(exec_role='COO', then=models.Value(4)), default=models.Value(99), output_field=models.IntegerField()), 'name']},
        ),
    ]
