# Generated by Django 5.1.7 on 2025-06-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_position_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='industry_group',
            field=models.CharField(choices=[('TMT', 'Tech, Media & Telecom'), ('RELG', 'Real Estate, Gaming & Lodging'), ('FI', 'Financial Institutions'), ('HLS', 'Healthcare & Life Sciences'), ('CR', 'Consumer & Retail'), ('NR', 'Natural Resources'), ('IND', 'Industrials'), ('NONE', 'None')], default='NONE', max_length=5),
        ),
    ]
